# ===================================================================
#  WhalesLauncher - create desktop / start-menu shortcuts.
#
#  Called by the shortcut .bat in the project root; can also be run
#  directly, from any working directory:
#     powershell -NoProfile -ExecutionPolicy Bypass -File <abs path>\scripts\make-shortcut.ps1
#
#  !! PURE ASCII, NO BOM ON PURPOSE. !!
#  This file is handed to powershell.exe, which is Windows PowerShell 5.1
#  on a stock machine. 5.1 reads files WITHOUT a BOM as ANSI, so UTF-8
#  Chinese in a comment can decode into quote characters and break
#  parsing (measured: "Unexpected token '}' in expression or statement"
#  pointing at the else-branch of an ordinary if/else). Keeping this file
#  pure ASCII makes it immune to the code page question entirely - a BOM
#  would fix it too, but a BOM is one careless rewrite away from being
#  silently dropped again.
#
#  All Chinese that must reach the user is printed by scripts\launch.mjs
#  (launched by WhalesLauncher.vbs), never from here.
#
#  Design notes:
#    * the shortcut points at wscript.exe + WhalesLauncher.vbs, NOT at
#      the .bat: a console window would flash on every launch otherwise;
#    * icon comes from assets/whales.ico when present (generated by
#      scripts/make-icon.mjs), else falls back to electron.exe;
#    * the Start Menu copy is what makes the app findable from Start
#      search - that needs no extra privileges. Pinning to the taskbar
#      needs an undocumented verb, so it is only suggested, never done.
# ===================================================================
$ErrorActionPreference = 'Stop'

# This script lives in <root>\scripts\, so the project root is two levels up.
# Derived from the script's own path, never from the current directory.
# $PSCommandPath is always set when PowerShell runs a script with -File.
$selfPath = $PSCommandPath
if ([string]::IsNullOrEmpty($selfPath)) { $selfPath = $MyInvocation.MyCommand.Path }
if ([string]::IsNullOrEmpty($selfPath)) {
  [Console]::Error.WriteLine('Cannot determine this script own path; pass it with -File.')
  exit 1
}
$root = (Resolve-Path -LiteralPath (Split-Path -Parent (Split-Path -Parent $selfPath))).Path

$vbs = Join-Path $root 'WhalesLauncher.vbs'
$ico = Join-Path $root 'assets\whales.ico'
$electron = Join-Path $root 'node_modules\electron\dist\electron.exe'
$wscript = Join-Path $env:SystemRoot 'System32\wscript.exe'

if (-not (Test-Path -LiteralPath $vbs)) {
  [Console]::Error.WriteLine("WhalesLauncher.vbs not found in the project root: $vbs")
  exit 1
}
if (-not (Test-Path -LiteralPath $electron)) {
  [Console]::Error.WriteLine("Electron runtime not found: $electron")
  [Console]::Error.WriteLine('Run "npm install" in the project root first.')
  exit 1
}

$iconPath = if (Test-Path -LiteralPath $ico) { $ico } else { $electron }

function New-WhalesShortcut {
  param([Parameter(Mandatory = $true)][string]$LinkPath)

  $dir = Split-Path -Parent $LinkPath
  if (-not (Test-Path -LiteralPath $dir)) {
    New-Item -ItemType Directory -Path $dir -Force | Out-Null
  }

  $shell = New-Object -ComObject WScript.Shell
  $link = $shell.CreateShortcut($LinkPath)
  $link.TargetPath = $wscript
  $link.Arguments = '"' + $vbs + '"'
  $link.WorkingDirectory = $root
  $link.IconLocation = "$iconPath,0"
  $link.Description = 'WhalesLauncher'
  $link.WindowStyle = 1
  $link.Save()
}

if ([string]::IsNullOrWhiteSpace($env:WHALES_SHORTCUT_NAME)) {
  $name = 'WhalesLauncher'
} else {
  $name = $env:WHALES_SHORTCUT_NAME
}

$targets = @(
  (Join-Path ([Environment]::GetFolderPath('Desktop')) "$name.lnk"),
  (Join-Path ([Environment]::GetFolderPath('Programs')) "$name.lnk")
)

$created = New-Object System.Collections.ArrayList
$failures = New-Object System.Collections.ArrayList
foreach ($target in $targets) {
  try {
    New-WhalesShortcut -LinkPath $target
    [void]$created.Add($target)
  } catch {
    [void]$failures.Add("$target -> $($_.Exception.Message)")
  }
}

# Fallback: a shortcut inside the project.
#
# Writing to the Desktop / Start Menu is a write outside the workspace, and
# restricted environments deny it (this machine's DSH file sandbox does -
# measured: "Unable to save shortcut"). Reporting a failure and stopping
# would leave the user with nothing, but a .lnk inside the project works
# just as well: drag it onto the taskbar (left-drag = pin, no extra
# privileges and no "Show more options" needed), the desktop, or the Start
# menu. The folder name is derived from the shortcut name so it stays
# ASCII here.
$fallback = $null
if ($created.Count -eq 0) {
  try {
    # Folder name for the in-project shortcut.
    #
    # It is Chinese on purpose ("kuai jie fang shi" = shortcut) because the
    # user sees it. It is BUILT FROM CODE POINTS rather than written literally:
    # this file must stay pure ASCII (see the header note), and an environment
    # variable carrying the literal text from the .bat turned out to be
    # unreliable - cmd mis-split the batch body around the UTF-8 bytes and the
    # stray half-lines ran as commands. Code points cannot be mis-decoded.
    $fallbackFolder = $env:WHALES_SHORTCUT_DIR
    if ([string]::IsNullOrWhiteSpace($fallbackFolder)) {
      $fallbackFolder = (-join ([char]0x5FEB, [char]0x6377, [char]0x65B9, [char]0x5F0F))
    }
    $fallbackDir = Join-Path $root $fallbackFolder
    if (-not (Test-Path -LiteralPath $fallbackDir)) {
      New-Item -ItemType Directory -Path $fallbackDir -Force | Out-Null
    }
    $fallback = Join-Path $fallbackDir "$name.lnk"
    New-WhalesShortcut -LinkPath $fallback
  } catch {
    [void]$failures.Add("$fallback -> $($_.Exception.Message)")
    $fallback = $null
  }
}

if ($created.Count -eq 0 -and $null -eq $fallback) {
  [Console]::Error.WriteLine('No shortcut could be created.')
  foreach ($line in $failures) { [Console]::Error.WriteLine("FAILED: $line") }
  exit 1
}

[Console]::Out.WriteLine('Shortcuts created:')
foreach ($item in $created) { [Console]::Out.WriteLine("  $item") }
if ($null -ne $fallback) {
  [Console]::Out.WriteLine("  $fallback")
}
foreach ($line in $failures) { [Console]::Out.WriteLine("SKIPPED: $line") }
[Console]::Out.WriteLine("Launches : $wscript `"$vbs`"")
[Console]::Out.WriteLine("Icon     : $iconPath")

if ($null -ne $fallback) {
  [Console]::Out.WriteLine('')
  [Console]::Out.WriteLine('The Desktop / Start Menu could not be written to from this shell,')
  [Console]::Out.WriteLine('so the shortcut was created inside the project instead. Drag it to')
  [Console]::Out.WriteLine('the taskbar, the desktop or the Start menu yourself.')
}

if ($env:WHALES_SANDBOXED -eq '1') {
  [Console]::Out.WriteLine('')
  [Console]::Out.WriteLine('NOTE: this shell is sandboxed (DSH_* environment detected), so')
  [Console]::Out.WriteLine('      the paths above may be redirected copies rather than the real')
  [Console]::Out.WriteLine('      Desktop / Start Menu. Re-run the bat from an ordinary terminal')
  [Console]::Out.WriteLine('      to place the shortcuts for real.')
}

exit 0
